### ISSUE TITLE
Retrofit - Explicit termination method 'close' not called

### ISSUE THREAD

**Issue by alexitelman** [multi-os-engine/multi-os-engine#12]
When using retrofit - the log is filled with these errors, although everything works:

```
System 5 A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
System 5 java.lang.Throwable: Explicit termination method 'close' not called
	at dalvik.system.CloseGuard.open(CloseGuard.java:180)
	at com.android.org.conscrypt.Platform.closeGuardOpen(Platform.java:198)
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:299)
	at com.squareup.okhttp.Connection.upgradeToTls(Connection.java:242)
	at com.squareup.okhttp.Connection.connect(Connection.java:159)
	at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:175)
	at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:120)
	at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:330)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:319)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
	at com.squareup.okhttp.Call.getResponse(Call.java:271)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
	at com.squareup.okhttp.recipes.RequestBodyCompression$GzipRequestInterceptor.intercept(RequestBodyCompression.java:45)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:225)
	at [##MuvixClass##]$1.intercept([##MuvixClass##]:89)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:225)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
	at com.squareup.okhttp.Call.execute(Call.java:79)
	at retrofit.client.OkClient.execute(OkClient.java:53)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
```

Need to either fix this or somehow filter out these errors from the log.. It's very disturbing when debugging.

**Comment by muvixalex** [comment]
+1

**Comment by muvixalex** [comment]
+1

**Comment by muvixalex** [comment]
Please add the 'ANDROID_LOG_TAGS' environment variable by default to the xcode project and/or intellij run configuration

**Comment by liliomk** [comment]
This is a bug in Retrofit and not in MOE. The output of these warnings can be disabled using the ANDROID_LOG_TAGS environment variable in Info.plist (See Issue #48)
