### ISSUE TITLE
"java.io.tmpdir" is set to "/tmp" by default on MOE

### ISSUE THREAD

**Issue by Berstanio** [multi-os-engine/multi-os-engine#183]
"java.io.tmpdir" is set to "/tmp" by default on MOE. 
https://github.com/multi-os-engine/libcore/blob/eae58129e020f95e9b4a506cea4cc90cc21b09a3/luni/src/main/java/java/lang/System.java#L851-L853
However, on iOS this path is invalid as a temporary directory.

This leads to errors like this:
createTempDirectory hangs indefinitly and createTempFile throws a error like:
```
java.io.FileNotFoundException: /tmp/random-name9074725035171402104.irrelevant: open failed: EPERM (Operation not permitted)
[...]
Caused by: java.io.FileNotFoundException: /tmp/random-name9074725035171402104.irrelevant: open failed: EPERM (Operation not permitted)
	at libcore.io.IoBridge.open(IoBridge.java:462)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:115)
	at desugar.sun.nio.fs.DesugarSeekableByteChannel.create(DesugarSeekableByteChannel.java:44)
	at desugar.sun.nio.fs.DesugarLinuxFileSystemProvider.newByteChannel(DesugarLinuxFileSystemProvider.java:176)
	at desugar.sun.nio.fs.DesugarLinuxFileSystemProvider.newByteChannel(DesugarLinuxFileSystemProvider.java:59)
	at java.nio.file.Files.newByteChannel(Files.java:372)
	at java.nio.file.Files.createFile(Files.java:649)
	at java.nio.file.TempFileHelper.create(TempFileHelper.java:137)
	at java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:160)
	at java.nio.file.Files.createTempFile(Files.java:914)
	at com.fittonia.chigginblazzder.IOSLauncher$$ExternalSyntheticApiModelOutline0.m(R8$$SyntheticClass)
	at com.fittonia.chigginblazzder.IOSLauncher.extractFileFromResources(IOSLauncher.java:32)
	at com.fittonia.chigginblazzder.IOSLauncher.createApplication(IOSLauncher.java:56)
	... 5 more
Caused by: android.system.ErrnoException: open failed: EPERM (Operation not permitted)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:187)
	at libcore.io.IoBridge.open(IoBridge.java:448)
	... 17 more
```

**Comment by Berstanio** [comment]
Seems like there is a iOS/macOS env variable that we can use, "TMPDIR"
https://chaosinmotion.com/2012/03/26/how-do-i-know-what-environment-variables-are-on-ios/

**Comment by sdyura** [comment]
in my app there are some libs that need "java.io.tmpdir" to be valid so i do this at startup:

```
        NSArray tmpData = Foundation.NSSearchPathForDirectoriesInDomains(NSSearchPathDirectory.CachesDirectory, NSSearchPathDomainMask.UserDomainMask, true);
        String cachesDirectory = (String)tmpData.objectAtIndex(0);
        System.setProperty("java.io.tmpdir", cachesDirectory);
```

then anything that needs it set correctly will work fine, and this also means that if the system decides it needs more space, it can delete those files for the app

**Comment by Berstanio** [comment]
But thats is a cache directory, not a temp directory.
I think MOE should set the "java.io.tmpdir" to a real temporary directory by default, because that is what a user would expect.

**Comment by sdyura** [comment]
ive also found NSTemporaryDirectory

https://developer.apple.com/documentation/foundation/1409211-nstemporarydirectory?language=objc

String tmpDir = apple.foundation.c.Foundation.NSTemporaryDirectory()

maybe that would be the correct thing to use

**Comment by Berstanio** [comment]
Yes, that is also the proposed solution used in the linked pr.
