### ISSUE TITLE
Libgdx build problem

### ISSUE THREAD

**Issue by reime005** [multi-os-engine/multi-os-engine#37]
Here is my error log:

```
:ios:moeMainProGuard UP-TO-DATE
:ios:moeMainRetrolambda
 FAILED
###########
# ERROR LOG
###########

Retrolambda 2.0.2-SNAPSHOT
Bytecode version: 51 (Java 7)
Default methods:  true
NatJ support:     true
Input directory:  ...
Output directory: ...
Classpath:        ...
Error! Failed to transform some classes
java.lang.RuntimeException: java.lang.ClassNotFoundException: com.intel.moe.natj.objc.ann.Selector
	at org.moe.retrolambda.natj.NatJRuntime.getClassFor(NatJRuntime.java:225)
	at org.moe.retrolambda.natj.AnnotationHelper.add(AnnotationHelper.java:40)
	at org.moe.retrolambda.natj.AddMissingAnnotations$1.visitAnnotation(AddMissingAnnotations.java:94)
	at net.orfjackal.retrolambda.asm.MethodVisitor.visitAnnotation(MethodVisitor.java:150)
	at net.orfjackal.retrolambda.asm.ClassReader.readMethod(ClassReader.java:974)
	at net.orfjackal.retrolambda.asm.ClassReader.accept(ClassReader.java:693)
	at net.orfjackal.retrolambda.asm.ClassReader.accept(ClassReader.java:506)
	at net.orfjackal.retrolambda.Transformers.transform(Transformers.java:112)
	at net.orfjackal.retrolambda.Transformers.backportClass(Transformers.java:51)
	at net.orfjackal.retrolambda.Retrolambda.run(Retrolambda.java:76)
	at net.orfjackal.retrolambda.Main.main(Main.java:26)
Caused by: java.lang.ClassNotFoundException: com.intel.moe.natj.objc.ann.Selector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.orfjackal.retrolambda.NonDelegatingClassLoader.loadClass(NonDelegatingClassLoader.java:27)
	at org.moe.retrolambda.natj.NatJRuntime.getClassFor(NatJRuntime.java:223)
	... 10 more
```

**Comment by kisg** [comment]
Support thread on the forum: https://discuss.multi-os-engine.org/t/libgdx-build-problem/96

**Comment by Tom-Ski** [comment]
LibGDX backend is a WIP, feel free to close this as we have issues on our end.

**Comment by kisg** [comment]
LibGDX backend in 1.9.5-SNAPSHOT now should work properly, see instructions here: https://discuss.multi-os-engine.org/t/experimental-testing-libgdx-with-moe-1-1-x/112

Reopen issue, if it still persist.
