### ISSUE TITLE
OutOfMemoryError when building with new (1.1) MOE version

### ISSUE THREAD

**Issue by muvixalex** [multi-os-engine/multi-os-engine#44]
After I upgraded from 1.0.710 to 1.1+ (uninstalled the old one first with the uninstall app, then installed the new IntelliJ plugin, updated my build.gradle like in a new template project, changed all com.intel.moe imports to org.moe),
I can't build our MOE project anymore, I'm getting an OutOfMemory exception after about a minute or two:

```
UNEXPECTED TOP-LEVEL ERROR:
java.lang.OutOfMemoryError: Java heap space: failed reallocation of scalar replaced objects
	at java.util.HashSet.<init>(HashSet.java:105)
	at com.android.dx.ssa.Dominators.compress(Dominators.java:121)
	at com.android.dx.ssa.Dominators.eval(Dominators.java:160)
	at com.android.dx.ssa.Dominators.run(Dominators.java:207)
	at com.android.dx.ssa.Dominators.make(Dominators.java:90)
	at com.android.dx.ssa.DomFront.run(DomFront.java:86)
	at com.android.dx.ssa.SsaConverter.placePhiFunctions(SsaConverter.java:297)
	at com.android.dx.ssa.SsaConverter.convertToSsaMethod(SsaConverter.java:51)
	at com.android.dx.ssa.Optimizer.optimize(Optimizer.java:98)
	at com.android.dx.ssa.Optimizer.optimize(Optimizer.java:72)
	at com.android.dx.dex.cf.CfTranslator.processMethods(CfTranslator.java:297)
	at com.android.dx.dex.cf.CfTranslator.translate0(CfTranslator.java:137)
	at com.android.dx.dex.cf.CfTranslator.translate(CfTranslator.java:93)
	at com.android.dx.command.dexer.Main.processClass(Main.java:729)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
	at com.android.dx.command.dexer.Main.access$300(Main.java:82)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:170)
	at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)
	at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)
	at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)
	at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)
	at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)
	at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ios:moeMainDex'.
> Task failed, you can find the log file here: /Users/alex/muvix/ios/build/moe/main/dex/Dex.log

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by kisg** [comment]
In MOE 1.1 we removed the extra "-Xmx4096M" from the dx command line. Can you please try to change this parameter in /Users/yourusername/.moe/moe-sdk-1.1.0/tools/dx script (the defaultMx variable)? We are contemplating to raising it back to 2G or 4G. Could you please try with -Xmx2048M as well to see if that would work for you?

**Comment by muvixalex** [comment]
I tried with 2048, I don't get the OutOfMemory error but I get 'MOE/MOE.h' file not found in main.cpp

**Comment by liliomk** [comment]
In MOE 1.1 the Xcode project was changed:
- you need the build.xcconfig from a new MOE 1.1 Xcode project
- you also need to replace the custom "Compile Sources (MOE)" build script phase in the Xcode project from a new MOE 1.1 project

We recommend to create a new Xcode project and move over the files, if possible.

**Comment by muvixalex** [comment]
The project is quite complex by now.. So moving the files is a last resort really.
I applied the 2 changes you said, but still getting the 'MOE/MOE.h' file not found error :-(

**Comment by liliomk** [comment]
Please make sure in your Xcode project settings the framework search paths, header search paths, other linker flags, etc. are set correctly. These settings are also mostly copyable from a new empty project.

**Comment by muvixalex** [comment]
All of these seem ok to me.

**Comment by liliomk** [comment]
If you can PM send me your Xcode project (only the *.xcodeproj file), I'll try to patch it. I have an idea what the issue may be, but I don't know an easy way to fix it other than manually edit it.

**Comment by muvixalex** [comment]
Sent by email

**Comment by liliomk** [comment]
In your build.xcconfig file, what value does this have? MOE_FRAMEWORK_PATH

**Comment by muvixalex** [comment]
MOE_FRAMEWORK_PATH = ${MOE_PROJECT_BUILD_DIR}/moe/sdk/sdk/${PLATFORM_NAME}

**Comment by liliomk** [comment]
Your Xcode project seems to be correct, my assumption is MOE_PROJECT_BUILD_DIR doesn't point to the correct place.

**Comment by muvixalex** [comment]
I think I need to change this:
MOE_PROJECT_DIR = ${SRCROOT}/../..
to this:
MOE_PROJECT_DIR = ${SRCROOT}/..

**Comment by muvixalex** [comment]
Our MOE project structure is:

moe-ios
       - build
       - src
       - xcode
                - Muvix.xcodeproj

**Comment by liliomk** [comment]
Then I think it should be:
MOE_PROJECT_DIR = ${SRCROOT}
MOE_PROJECT_BUILD_DIR = ${MOE_PROJECT_DIR}/build

**Comment by muvixalex** [comment]
The build succeeds with MOE_PROJECT_DIR = ${SRCROOT}/..
But now the app closes immediately as it opens.

It crashed in main.cpp on the last line (return moevm(argc, argv);) with EXC_BAD_ACCESS(code=1, address=0x60)

And also I am getting this warning: (I added moe.sdk.trim_all in the build phase like before)

The 'moe.sdk.trim_all' project property will be removed, please use 'moe.proguardLevel=all' instead!

**Comment by muvixalex** [comment]
For other people: 
I also needed to change the Inte.MOE.Main.Class to just MOE.Main.Class in the Info.plist

Now it works.
