### ISSUE TITLE
Duplicate entries in archive

### ISSUE THREAD

**Issue by dzungpv** [multi-os-engine/multi-os-engine#58]
I try setting moe.proguardLevel='all' to make app smaller but it get this exception:
````
System 6 Unable to open boot classpath entry: /var/containers/Bundle/Application/E2C42C43-951D-4D47-883D-FB8047D375E7/ios-moe.app/application.jar
System 6 java.io.IOException: Duplicate entries in archive
	at java.util.jar.StrictJarFile.nativeOpenJarFile(Native Method)
	at java.util.jar.StrictJarFile.<init>(StrictJarFile.java:61)
	at libcore.io.ClassPathURLStreamHandler.<init>(ClassPathURLStreamHandler.java:57)
	at java.lang.VMClassLoader.createBootClassPathUrlHandlers(VMClassLoader.java:48)
	at java.lang.VMClassLoader.<clinit>(VMClassLoader.java:31)
	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:373)
	at java.lang.BootClassLoader.loadClass(ClassLoader.java:849)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:480)
	at libcore.reflect.InternalNames.getClass(InternalNames.java:53)
	at java.lang.Class.getDexCacheType(Class.java:521)
	at java.lang.reflect.Method.getReturnType(Method.java:173)
	at java.lang.Class.getDeclaredMethods(Class.java:717)
	at org.moe.natj.objc.ObjCRuntime.registerClass(Native Method)
	at org.moe.natj.objc.ObjCRuntime.doRegistration(ObjCRuntime.java:73)
	at org.moe.natj.general.NatJ.register(NatJ.java:265)
	at apple.NSObject.<clinit>(NSObject.java:65)

````

**Comment by liliomk** [comment]
Please retry with moe-gradle 1.2.2 plugin

```
classpath 'org.multi-os-engine:moe-gradle:1.2.2'
```

**Comment by dzungpv** [comment]
@liliomk 1.2.2 work fine, i will close this now.
