### ISSUE TITLE
USE "UIApplication.sharedApplication().delegate().window() " CRASH in libgdx 1.9.5

### ISSUE THREAD

**Issue by tianqiujie** [multi-os-engine/multi-os-engine#71]
USE "UIApplication.sharedApplication().delegate().window() " CRASH in libgdx 1.9.5

moe gradle plugins 1.2.5

HI, 
     Our sdk use the 
```
 [[[UIApplication sharedApplication] delegate] window]
```
by object-c in our sdk.framework.

And now run in android stuido, the app will crashed, by error:
```
2016-12-16 17:49:54.975 ios-moe[13408:413201] documentDirectory=/Users/tian/Library/Developer/CoreSimulator/Devices/29F823F0-5F5E-4E1E-ABA6-D31FDD1C9A14/data/Containers/Data/Application/77572173-63F3-4EA8-8AAB-83B268F98551/Documents
java.lang.AbstractMethodError: abstract method "apple.uikit.UIWindow apple.uikit.protocol.UIApplicationDelegate.window()"
	at net.mwplay.nativefont.test.IOSMoeLauncher.applicationDidFinishLaunchingWithOptions(IOSMoeLauncher.java:36)
	at apple.uikit.c.UIKit.UIApplicationMain(Native Method)
	at net.mwplay.nativefont.test.IOSMoeLauncher.main(IOSMoeLauncher.java:42)
art I 13409 413263 /Volumes/SSD/gh-moe-master-1.2.5/aosp/art/runtime/parsed_options.cc:449] setting boot class path to /Users/tian/Library/Developer/CoreSimulator/Devices/29F823F0-5F5E-4E1E-ABA6-D31FDD1C9A14/data/Containers/Bundle/Application/2D3BDE32-E26D-46FC-B75F-2C7B6ADD4CBD/ios-moe.app/application.jar:/Users/tian/Library/Developer/CoreSimulator/Devices/29F823F0-5F5E-4E1E-ABA6-D31FDD1C9A14/data/Containers/Bundle/Application/2D3BDE32-E26D-46FC-B75F-2C7B6ADD4CBD/ios-moe.app
```

**Comment by liliomk** [comment]
This issue was marked as solved in the forum
